# Generated by Django 3.2.5 on 2021-10-05 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 20, 49, 53, 639104)),
        ),
    ]
