# Generated by Django 3.2.5 on 2021-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Нормальный'), (3, 'Высокий')], default=2, null=True),
        ),
    ]
